import { Gender, BabyName } from './types';

/**
 * Seznam jmen s jejich významem a původem.
 */
const rawDataset: [string, string, string][] = [
  // --- MUŽSKÁ JMÉNA ---
  ["MUZ", "ADAM", "Jméno hebrejského původu, které v překladu znamená 'člověk' nebo 'pozemšťan'."],
  ["MUZ", "ALEŠ", "Česká podoba řeckého jména Alexej, znamenající 'obránce' nebo 'pomocník'."],
  ["MUZ", "ALOIS", "Jméno staroněmeckého původu, které se vykládá jako 'slavný bojovník'."],
  ["MUZ", "ANDREJ", "Slovanská varianta řeckého jména Andreas, což znamená 'statečný' či 'mužný'."],
  ["MUZ", "ANTONÍN", "Jméno latinského původu, které znamená 'vynikající' nebo 'vznešený'."],
  ["MUZ", "BEDŘICH", "Germánské jméno, které v překladu znamená 'mírumilovný vládce'."],
  ["MUZ", "BOHUMIL", "Slovanské jméno s jasným významem 'Bohu milý'."],
  ["MUZ", "BOHUSLAV", "Staré slovanské jméno znamenající 'ten, který slaví Boha'."],
  ["MUZ", "BŘETISLAV", "Slovanské jméno, které se vykládá jako 'slavný bojovým rykem'."],
  ["MUZ", "CYRIL", "Jméno řeckého původu, které v překladu znamená 'pán' nebo 'vznešený'."],
  ["MUZ", "ČESTMÍR", "Slovanské jméno vyjadřující 'ctitele míru' nebo 'toho, kdo ctí svět'."],
  ["MUZ", "DALIBOR", "Staré české jméno znamenající 'toho, kdo se bije v dálce'."],
  ["MUZ", "DAN", "Hebrejské jméno, které v překladu znamená 'soudce'."],
  ["MUZ", "DANIEL", "Biblické jméno hebrejského původu znamenající 'Bůh je můj soudce'."],
  ["MUZ", "DAVID", "Velmi oblíbené hebrejské jméno, které znamená 'miláček' nebo 'přítel'."],
  ["MUZ", "DOMINIK", "Latinské jméno, které se vykládá jako 'pánův' či 'zasvěcený Bohu'."],
  ["MUZ", "DRAHOMÍR", "Slovanské jméno znamenající 'ten, komu je drahý mír'."],
  ["MUZ", "DUŠAN", "Jméno slovanského původu odvozené od slova 'duše' nebo 'dech'."],
  ["MUZ", "EDUARD", "Anglosaské jméno, které znamená 'strážce majetku' nebo 'bohatý ochránce'."],
  ["MUZ", "EMIL", "Latinské jméno, které se vykládá jako 'pracovitý' nebo 'horlivý'."],
  ["MUZ", "ERIK", "Skandinávské jméno, které v překladu znamená 'čestný vládce'."],
  ["MUZ", "EVŽEN", "Jméno řeckého původu, které znamená 'urozený' nebo 'dobře narozený'."],
  ["MUZ", "FILIP", "Řecké jméno, které v doslovném překladu znamená 'milovník koní'."],
  ["MUZ", "FRANTIŠEK", "Jméno italského původu znamenající 'malý Francouz' nebo 'svobodný muž'."],
  ["MUZ", "GABRIEL", "Hebrejské jméno, které se vykládá jako 'Bůh je má síla'."],
  ["MUZ", "GUSTAV", "Jméno švédského původu, které znamená 'opora Gótů'."],
  ["MUZ", "HANUŠ", "Staroněmecká a česká varianta jména Jan, znamenající 'Bůh je milostivý'."],
  ["MUZ", "HUBERT", "Germánské jméno, které v překladu znamená 'jasná mysl'."],
  ["MUZ", "HYNEK", "Česká varianta německého jména Heinrich, znamenající 'vládce domu'."],
  ["MUZ", "IVAN", "Slovanská podoba jména Jan, která znamená 'Bůh je milostivý'."],
  ["MUZ", "IVO", "Jméno germánského původu odvozené od stromu tisu."],
  ["MUZ", "JÁCHYM", "Hebrejské jméno, které znamená 'Bůh ho postaví' nebo 'Bůh ho upevní'."],
  ["MUZ", "JAKUB", "Velmi časté hebrejské jméno znamenající 'ten, kdo se drží za patu'."],
  ["MUZ", "JAN", "Jedno z nejrozšířenějších jmen, v hebrejštině znamená 'Bůh je milostivý'."],
  ["MUZ", "JAREK", "Domácká podoba jmen začínajících na Jar-, znamenající 'silný' nebo 'bujný'."],
  ["MUZ", "JAROMÍR", "Slovanské jméno, které se vykládá jako 'slavný silou' nebo 'milující mír'."],
  ["MUZ", "JAROSLAV", "Starobylé slovanské jméno znamenající 'ten, kdo slaví jaro' nebo 'silný'."],
  ["MUZ", "JERONÝM", "Řecké jméno, které v překladu znamená 'svaté jméno'."],
  ["MUZ", "JINDŘICH", "Germánské jméno, které v překladu znamená 'vládce domu'."],
  ["MUZ", "JIŘÍ", "Jméno řeckého původu, které v doslovném překladu znamená 'zemědělec'."],
  ["MUZ", "JOSEF", "Hebrejské jméno, které se vykládá jako 'Bůh ti přidá'."],
  ["MUZ", "JOZEF", "Varianta jména Josef, znamenající 'Bůh ti přidá'."],
  ["MUZ", "KAMIL", "Jméno latinského původu, které znamenalo 'urozený hoch' při obřadech."],
  ["MUZ", "KAREL", "Starogermánské jméno, které v překladu znamená 'svobodný muž'."],
  ["MUZ", "KRYŠTOF", "Řecké jméno, které znamená 'ten, kdo nese Krista'."],
  ["MUZ", "KVĚTOSLAV", "České jméno vytvořené v 19. století jako oslava květů a jara."],
  ["MUZ", "LADISLAV", "Slovanské jméno, které se vykládá jako 'ten, kdo vládne slavně'."],
  ["MUZ", "LEOŠ", "Česká varianta jména Leo, která v latině znamená 'lev'."],
  ["MUZ", "LIBOR", "Latinské jméno, které v překladu znamená 'svobodný' nebo 'libý'."],
  ["MUZ", "LUBOŠ", "Slovanské jméno odvozené od slova 'libý' nebo 'milovaný'."],
  ["MUZ", "LUBOMÍR", "Slovanské jméno, které znamená 'ten, kdo miluje mír'."],
  ["MUZ", "LUKÁŠ", "Jméno latinského původu znamenající 'pocházející z Lukánie'."],
  ["MUZ", "LUMÍR", "Slovanské jméno, které se vykládá jako 'mírný' nebo 'svět'."],
  ["MUZ", "MAREK", "Latinské jméno odvozené od boha války Marta, znamená 'bojovník'."],
  ["MUZ", "MARIAN", "Jméno latinského původu, které se vykládá jako 'patřící k rodu Mariů'."],
  ["MUZ", "MARTIN", "Latinské jméno odvozené od boha války Marta, znamená 'bojovný'."],
  ["MUZ", "MATĚJ", "Hebrejské jméno, které v překladu znamená 'dar Boží'."],
  ["MUZ", "MATYÁŠ", "Hebrejské jméno, které v překladu znamená 'dar Boží'."],
  ["MUZ", "MAXIM", "Latinské jméno, které v překladu znamená 'největší'."],
  ["MUZ", "MICHAL", "Hebrejské jméno, které v překladu znamená 'kdo je jako Bůh?'."],
  ["MUZ", "MIKULÁŠ", "Řecké jméno, které v překladu znamená 'vítěz nad lidem'."],
  ["MUZ", "MILAN", "Slovanské jméno odvozené od slova 'milý'."],
  ["MUZ", "MILOŠ", "Slovanské jméno s významem 'milý' nebo 'přívětivý'."],
  ["MUZ", "MILOSLAV", "Slovanské jméno znamenající 'ten, kdo miluje slávu' nebo 'milý'."],
  ["MUZ", "MIROSLAV", "Slovanské jméno, které znamená 'slavný mírem'."],
  ["MUZ", "OLDŘICH", "Germánské jméno, které znamená 'bohatý vládce'."],
  ["MUZ", "ONDŘEJ", "Řecké jméno, které v překladu znamená 'mužný' nebo 'statečný'."],
  ["MUZ", "OSKAR", "Jméno germánského původu znamenající 'boží kopí'."],
  ["MUZ", "OTA", "Germánské jméno, které v překladu znamená 'majetek' nebo 'bohatství'."],
  ["MUZ", "OTAKAR", "Germánské jméno, které znamená 'střežící majetek'."],
  ["MUZ", "PATRIK", "Latinské jméno, které v překladu znamená 'šlechtic' nebo 'urozený'."],
  ["MUZ", "PAVEL", "Latinské jméno, které v překladu znamená 'malý' nebo 'skromný'."],
  ["MUZ", "PETR", "Řecké jméno, které v překladu znamená 'skála' nebo 'kámen'."],
  ["MUZ", "PŘEMYSL", "Staré české jméno znamenající 'ten, kdo vše dobře promýšlí'."],
  ["MUZ", "RADEK", "Slovanské jméno odvozené od slova 'radost' nebo 'radovat se'."],
  ["MUZ", "RADIM", "Slovanské jméno, které v překladu znamená 'ten, kdo má rád mír'."],
  ["MUZ", "RADOMÍR", "Slovanské jméno znamenající 'ten, kdo se raduje z míru'."],
  ["MUZ", "RADOSLAV", "Slovanské jméno, které se vykládá jako 'slavící radost'."],
  ["MUZ", "RADVAN", "Staré české jméno, které znamená 'ten, kdo se raduje'."],
  ["MUZ", "RENE", "Jméno latinského původu, které v překladu znamená 'znovuzrozený'."],
  ["MUZ", "RICHARD", "Germánské jméno, které znamená 'mocný vládce' nebo 'bohatý'."],
  ["MUZ", "ROBERT", "Germánské jméno, které v překladu znamená 'slávou zářící'."],
  ["MUZ", "ROMAN", "Latinské jméno, které v doslovném překladu znamená 'Říman'."],
  ["MUZ", "ROSTISLAV", "Slovanské jméno, které znamená 'ten, kdo šíří slávu'."],
  ["MUZ", "RUDOLF", "Germánské jméno, které v překladu znamená 'slavný vlk'."],
  ["MUZ", "SAMUEL", "Hebrejské jméno, které znamená 'Bůh mě vyslyšel'."],
  ["MUZ", "SEBASTIAN", "Řecké jméno, které v překladu znamená 'vznešený' nebo 'uctívaný'."],
  ["MUZ", "SLAVOMÍR", "Slovanské jméno znamenající 'slavný mírem'."],
  ["MUZ", "STANISLAV", "Slovanské jméno, které se vykládá jako 'staň se slavným'."],
  ["MUZ", "SVATOPLUK", "Slovanské jméno znamenající 'silný v branném lidu'."],
  ["MUZ", "SVATOSLAV", "Slovanské jméno znamenající 'silný v slávě'."],
  ["MUZ", "ŠIMON", "Hebrejské jméno, které v překladu znamená 'naslouchající'."],
  ["MUZ", "ŠTĚPÁN", "Řecké jméno, které v doslovném překladu znamená 'ověnčený'."],
  ["MUZ", "TADEÁŠ", "Jméno aramejského původu, které znamená 'rozvážný' nebo 'odvážný'."],
  ["MUZ", "TEODOR", "Řecké jméno, které v překladu znamená 'dar Boží'."],
  ["MUZ", "TOMÁŠ", "Aramejské jméno, které v doslovném překladu znamená 'blíženec' nebo 'dvojče'."],
  ["MUZ", "VÁCLAV", "Staré české jméno, které znamená 'více slavný'."],
  ["MUZ", "VALENTÝN", "Latinské jméno, které v překladu znamená 'zdravý' nebo 'silný'."],
  ["MUZ", "VALTR", "Germánské jméno, které v překladu znamená 'vládce vojska'."],
  ["MUZ", "VAVŘINEC", "Latinské jméno znamenající 'ověnčený vavřínem'."],
  ["MUZ", "VENDELÍN", "Jméno germánského původu znamenající 'poutník' nebo 'Polabský Slovan'."],
  ["MUZ", "VĚROSLAV", "České jméno znamenající 'slavící víru' nebo 'v věrnosti slavný'."],
  ["MUZ", "VIKTOR", "Latinské jméno, které v doslovném překladu znamená 'vítěz'."],
  ["MUZ", "VILÉM", "Germánské jméno, které znamená 'vůlí chráněný'."],
  ["MUZ", "VINCENT", "Latinské jméno, které v překladu znamená 'vítězící'."],
  ["MUZ", "VÍT", "Latinské jméno odvozené od slova 'vita', což znamená 'život'."],
  ["MUZ", "VÍTĚZSLAV", "České jméno vytvořené jako oslava vítězství a slávy."],
  ["MUZ", "VLADIMÍR", "Slovanské jméno, které znamená 'velký vládce' nebo 'vládce světa'."],
  ["MUZ", "VLADISLAV", "Slovanské jméno, které znamená 'vládce slávy'."],
  ["MUZ", "VLASTIMIL", "České jméno znamenající 'ten, kdo miluje svou vlast'."],
  ["MUZ", "VOJTĚCH", "Slovanské jméno, které v překladu znamená 'útěcha vojska'."],
  ["MUZ", "VRATISLAV", "Staré české jméno znamenající 'navrať slávu'."],
  ["MUZ", "ZBYNĚK", "Slovanské jméno, které se vykládá jako 'posilující hněv' nebo 'zbytek'."],
  ["MUZ", "ZDENĚK", "České jméno odvozené od Zdislava, znamenající 'zde slavný'."],
  ["MUZ", "ZIKMUND", "Germánské jméno, které v překladu znamená 'vítězná ochrana'."],

  // --- ŽENSKÁ JMÉNA ---
  ["ZENA", "ADÉLA", "Germánské jméno, které v překladu znamená 'vznešená' nebo 'ušlechtilá'."],
  ["ZENA", "AGÁTA", "Řecké jméno, které v doslovném překladu znamená 'dobrá' či 'laskavá'."],
  ["ZENA", "ALENA", "Jméno nejasného původu, často vykládané jako 'pochodeň' nebo 'zářící'."],
  ["ZENA", "ALEXANDRA", "Řecké jméno, které v překladu znamená 'obránkyně lidstva'."],
  ["ZENA", "ALICE", "Jméno germánského původu, které znamená 'vznešená bytost'."],
  ["ZENA", "ALŽBĚTA", "Hebrejské jméno znamenající 'Bůh je má přísaha'."],
  ["ZENA", "AMÁLIE", "Latinské jméno, které se vykládá jako 'milostná' nebo 'líbezná'."],
  ["ZENA", "ANASTÁZIE", "Řecké jméno, které v překladu znamená 'vzkříšená'."],
  ["ZENA", "ANDĚLA", "Řecké jméno, které v překladu znamená 'posel Boží'."],
  ["ZENA", "ANDREA", "Jméno řeckého původu znamenající 'odvážná' nebo 'mužná'."],
  ["ZENA", "ANETA", "Hebrejské jméno (varianta Anny), které znamená 'milostivá'."],
  ["ZENA", "ANEŽKA", "Řecké jméno, které v překladu znamená 'čistá' nebo 'neposkvrněná'."],
  ["ZENA", "ANNA", "Hebrejské jméno, které v překladu znamená 'milostná' nebo 'líbezná'."],
  ["ZENA", "ANTONIE", "Latinské jméno, které se vykládá jako 'vynikající' nebo 'vznešená'."],
  ["ZENA", "APOLENA", "Jméno řeckého původu odvozené od boha světla Apollóna."],
  ["ZENA", "BARBORA", "Řecké jméno, které v doslovném překladu znamená 'cizinka'."],
  ["ZENA", "BEÁTA", "Latinské jméno, které v překladu znamená 'blažená' nebo 'šťastná'."],
  ["ZENA", "BERTA", "Germánské jméno, které v překladu znamená 'zářící' nebo 'skvělá'."],
  ["ZENA", "BLANKA", "Latinské jméno, které v doslovném překladu znamená 'bílá' či 'čistá'."],
  ["ZENA", "BLAŽENA", "Slovanské jméno, které se vykládá jako 'šťastná' nebo 'požehnaná'."],
  ["ZENA", "BOHDANA", "Slovanské jméno s významem 'darovaná Bohem'."],
  ["ZENA", "BOHUMILA", "Slovanské jméno s jasným významem 'Bohu milá'."],
  ["ZENA", "BOHUSLAVA", "Slovanské jméno znamenající 'Bohu sláva'."],
  ["ZENA", "BOŽENA", "Staré české jméno, které znamená 'Bohem obdařená'."],
  ["ZENA", "DAGMAR", "Skandinávské jméno, které v překladu znamená 'slavný den'."],
  ["ZENA", "DANA", "Hebrejské jméno, které v překladu znamená 'soudkyně'."],
  ["ZENA", "DANIELA", "Hebrejské jméno, které znamená 'Bůh je můj soudce'."],
  ["ZENA", "DARINA", "Slovanské jméno, které se vykládá jako 'dar' nebo 'darovaná'."],
  ["ZENA", "DENISA", "Jméno řeckého původu odvozené od boha vína Dionýsa."],
  ["ZENA", "DIANA", "Latinské jméno odvozené od bohyně lovu a měsíce."],
  ["ZENA", "DITA", "Domácká podoba jména Judita či Edita, znamenající 'bohatá'."],
  ["ZENA", "DOBROMILA", "Slovanské jméno znamenající 'tu, která má ráda dobro'."],
  ["ZENA", "DOMINIKA", "Latinské jméno, které se vykládá jako 'pánova' či 'zasvěcená Bohu'."],
  ["ZENA", "DORA", "Řecké jméno, které v překladu znamená 'dar'."],
  ["ZENA", "DOROTA", "Řecké jméno, které v doslovném překladu znamená 'dar Boží'."],
  ["ZENA", "DRAHOMÍRA", "Slovanské jméno znamenající 'tu, které je drahý mír'."],
  ["ZENA", "DRAHOSLAVA", "Slovanské jméno, které se vykládá jako 'drahá a slavná'."],
  ["ZENA", "EDITA", "Anglosaské jméno, které znamená 'bohatá a šťastná'."],
  ["ZENA", "ELENA", "Varianta jména Helena, znamenající 'světlo' nebo 'pochodeň'."],
  ["ZENA", "ELIŠKA", "Česká varianta hebrejského jména Alžběta, znamenající 'Bůh je má přísaha'."],
  ["ZENA", "EMMA", "Germánské jméno, které v překladu znamená 'vesmírná' nebo 'celistvá'."],
  ["ZENA", "ERIKA", "Skandinávské jméno, které v překladu znamená 'čestná vládne'."],
  ["ZENA", "ESTER", "Perské jméno, které v překladu znamená 'hvězda'."],
  ["ZENA", "EVA", "Hebrejské jméno, které v překladu znamená 'živá' nebo 'matka života'."],
  ["ZENA", "EVELÍNA", "Jméno keltského původu znamenající 'světlo' nebo 'radost'."],
  ["ZENA", "EVŽENIE", "Řecké jméno, které znamená 'urozená' nebo 'dobře narozená'."],
  ["ZENA", "FRANTIŠKA", "Italské jméno znamenající 'malá Francouzka' nebo 'svobodná'."],
  ["ZENA", "GABRIELA", "Hebrejské jméno, které se vykládá jako 'Bůh je má síla'."],
  ["ZENA", "GITA", "Zkrácenina jména Markéta, která v sanskrtu znamená 'píseň'."],
  ["ZENA", "HANA", "Hebrejské jméno, které v překladu znamená 'milostná' nebo 'líbezná'."],
  ["ZENA", "HEDVIKA", "Germánské jméno, které znamená 'vítězná v boji'."],
  ["ZENA", "HELENA", "Řecké jméno, které v doslovném překladu znamená 'pochodeň' nebo 'světlo'."],
  ["ZENA", "HERMÍNA", "Germánské jméno, které se vykládá jako 'bojovnice'."],
  ["ZENA", "IVANA", "Slovanská varianta jména Jana, znamenající 'Bůh je milostivý'."],
  ["ZENA", "IVETA", "Jméno germánského původu odvozené od stromu tisu."],
  ["ZENA", "IVONA", "Jméno germánského původu odvozené od stromu tisu."],
  ["ZENA", "IZABELA", "Varianta jména Alžběta, znamenající 'Bůh je má přísaha'."],
  ["ZENA", "JANA", "Hebrejské jméno, které v překladu znamená 'Bůh je milostivý'."],
  ["ZENA", "JARMILA", "Slovanské jméno znamenající 'milující jaro' nebo 'silná'."],
  ["ZENA", "JAROSLAVA", "Slovanské jméno znamenající 'tu, která slaví jaro' nebo 'silná'."],
  ["ZENA", "JINDŘIŠKA", "Germánské jméno, které v překladu znamená 'vládkyně domu'."],
  ["ZENA", "JIŘINA", "Řecké jméno, které v doslovném překladu znamená 'zemědělkyně'."],
  ["ZENA", "JITKA", "Hebrejské jméno, které v překladu znamená 'žena z Judeje'."],
  ["ZENA", "JOHANA", "Hebrejské jméno, které v překladu znamená 'Bůh je milostivý'."],
  ["ZENA", "JOLANA", "Jméno řeckého původu znamenající 'fialka' nebo 'květ'."],
  ["ZENA", "JOSEFA", "Hebrejské jméno, které se vykládá jako 'Bůh ti přidá'."],
  ["ZENA", "JUDITA", "Hebrejské jméno, které v překladu znamená 'žena z Judeje'."],
  ["ZENA", "JULIE", "Latinské jméno, které se vykládá jako 'zářící' nebo 'vlasatá'."],
  ["ZENA", "JUSTÝNA", "Latinské jméno, které v překladu znamená 'spravedlivá'."],
  ["ZENA", "KAMILA", "Latinské jméno znamenající 'urozená dívka' při obřadech."],
  ["ZENA", "KAROLÍNA", "Germánské jméno, které v překladu znamená 'svobodná žena'."],
  ["ZENA", "KATEŘINA", "Řecké jméno, které v překladu znamená 'čistá' nebo 'neposkvrněná'."],
  ["ZENA", "KLÁRA", "Latinské jméno, které v překladu znamená 'jasná' nebo 'zářící'."],
  ["ZENA", "KRISTÝNA", "Řecké jméno, které znamená 'křesťanka' nebo 'zasvěcená Kristu'."],
  ["ZENA", "KVĚTA", "České jméno vytvořené v 19. století jako oslava květů."],
  ["ZENA", "KVĚTOSLAVA", "České jméno vytvořené v 19. století jako oslava květů a jara."],
  ["ZENA", "LADA", "Slovanské jméno odvozené od staroslovanské bohyně krásy a lásky."],
  ["ZENA", "LADISLAVA", "Slovanské jméno znamenající 'tu, která vládne slavně'."],
  ["ZENA", "LENKA", "Zkrácenina jména Helena nebo Magdalena, znamená 'pochodeň' či 'věž'."],
  ["ZENA", "LEONA", "Latinské jméno, které v doslovném překladu znamená 'lvice'."],
  ["ZENA", "LIBUŠE", "Staré české jméno odvozené od slova 'libý' nebo 'milovaný'."],
  ["ZENA", "LINDA", "Germánské jméno, které v překladu znamená 'jemná' nebo 'mírná'."],
  ["ZENA", "LUCIE", "Latinské jméno odvozené od slova 'lux', což znamená 'světlo'."],
  ["ZENA", "LUDMILA", "Slovanské jméno s významem 'lidu milá'."],
  ["ZENA", "LYDIE", "Řecké jméno znamenající 'pocházející z Lýdie'."],
  ["ZENA", "MAGDALÉNA", "Hebrejské jméno znamenající 'pocházející z Magdaly'."],
  ["ZENA", "MAHULENA", "Uměle vytvořené jméno, které zpopularizoval Julius Zeyer."],
  ["ZENA", "MARCELA", "Latinské jméno odvozené od boha války Marta."],
  ["ZENA", "MARGITA", "Latinské jméno, které v překladu znamená 'perla'."],
  ["ZENA", "MARIE", "Hebrejské jméno s mnoha významy, nejčastěji 'milovaná Bohem'."],
  ["ZENA", "MARKÉTA", "Latinské jméno, které v překladu znamená 'perla'."],
  ["ZENA", "MARTA", "Aramejské jméno, které v překladu znamená 'paní domu' či 'hospodyně'."],
  ["ZENA", "MARTINA", "Latinské jméno odvozené od boha války Marta, znamená 'bojovná'."],
  ["ZENA", "MATYLDA", "Germánské jméno, které v překladu znamená 'mocná bojovnice'."],
  ["ZENA", "MICHAELA", "Hebrejské jméno, které v překladu znamená 'kdo je jako Bůh?'."],
  ["ZENA", "MILADA", "Slovanské jméno s významem 'mladá' nebo 'milá'."],
  ["ZENA", "MILENA", "Slovanské jméno odvozené od slova 'milá'."],
  ["ZENA", "MILOSLAVA", "Slovanské jméno znamenající 'tu, která miluje slávu'."],
  ["ZENA", "MILUŠE", "Slovanské jméno odvozené od slova 'milá'."],
  ["ZENA", "MIRKA", "Zkrácenina jména Miroslava, znamenající 'mírumilovná'."],
  ["ZENA", "MIROSLAVA", "Slovanské jméno, které v překladu znamená 'slavná mírem'."],
  ["ZENA", "MONIKA", "Řecké jméno, které se vykládá jako 'jediná' nebo 'osamělá'."],
  ["ZENA", "NAĎA", "Slovanské jméno, které v překladu znamená 'naděje'."],
  ["ZENA", "NADĚŽDA", "Slovanské jméno, které v překladu znamená 'naděje'."],
  ["ZENA", "NATÁLIE", "Latinské jméno, které znamená 'v den narození' (Páně)."],
  ["ZENA", "NELA", "Latinské jméno odvozené od jména Petronila či Kornélie."],
  ["ZENA", "NIKOLA", "Řecké jméno, které v překladu znamená 'vítězka nad lidem'."],
  ["ZENA", "NINA", "Jméno nejasného původu, často vykládané jako 'spanilá' či 'milá'."],
  ["ZENA", "OLGA", "Skandinávské jméno, které v překladu znamená 'svatá'."],
  ["ZENA", "OLIVIE", "Latinské jméno odvozené od olivovníku, symbolu míru."],
  ["ZENA", "OTÝLIE", "Germánské jméno, které v překladu znamená 'bohatá'."],
  ["ZENA", "PAVLA", "Latinské jméno, které v překladu znamená 'malá' nebo 'skromná'."],
  ["ZENA", "PAVLÍNA", "Latinské jméno, které v překladu znamená 'malá' nebo 'skromná'."],
  ["ZENA", "PETRA", "Řecké jméno, které v doslovném překladu znamená 'skála'."],
  ["ZENA", "RADKA", "Slovanské jméno odvozené od slova 'radost' nebo 'radovat se'."],
  ["ZENA", "RADMILA", "Slovanské jméno znamenající 'tu, která má ráda dobro'."],
  ["ZENA", "REGINA", "Latinské jméno, které v překladu znamená 'královna'."],
  ["ZENA", "RENÁTA", "Latinské jméno, které v překladu znamená 'znovuzrozená'."],
  ["ZENA", "ROMANA", "Latinské jméno, které v doslovném překladu znamená 'Římanka'."],
  ["ZENA", "RŮŽENA", "Latinské jméno odvozené od květiny růže."],
  ["ZENA", "SÁRA", "Hebrejské jméno, které v překladu znamená 'kněžna' nebo 'vznešená'."],
  ["ZENA", "SILVIE", "Latinské jméno, které v doslovném překladu znamená 'lesní'."],
  ["ZENA", "SIMONA", "Hebrejské jméno, které v překladu znamená 'naslouchající'."],
  ["ZENA", "SOŇA", "Ruská varianta jména Žofie, které znamená 'moudrost'."],
  ["ZENA", "STANISLAVA", "Slovanské jméno, které se vykládá jako 'staň se slavnou'."],
  ["ZENA", "STELA", "Latinské jméno, které v doslovném překladu znamená 'hvězda'."],
  ["ZENA", "SVATAVA", "Slovanské jméno, které znamená 'svatá' nebo 'silná'."],
  ["ZENA", "ŠÁRKA", "Staré české jméno odvozené od názvu Divoké Šárky v Praze."],
  ["ZENA", "ŠTĚPÁNKA", "Řecké jméno, které v doslovném překladu znamená 'ověnčený'."],
  ["ZENA", "TAŤÁNA", "Latinské jméno, které se vykládá jako 'ustavená' či 'tichá'."],
  ["ZENA", "TEREZA", "Řecké jméno, které v překladu znamená 'ochránkyně' či 'sklizeň'."],
  ["ZENA", "URSULA", "Latinské jméno, které v překladu znamená 'malá medvědice'."],
  ["ZENA", "VÁCLAVA", "Staré české jméno znamenající 'více slavná'."],
  ["ZENA", "VALÉRIE", "Latinské jméno, které v překladu znamená 'silná' nebo 'zdravá'."],
  ["ZENA", "VANDA", "Polské jméno, které pravděpodobně znamená 'voda' nebo 'vůdkyně'."],
  ["ZENA", "VĚRA", "Slovanské jméno s jasným významem 'víra' nebo 'věrná'."],
  ["ZENA", "VERONIKA", "Řecké jméno, které v překladu znamená 'přinášející vítězství'."],
  ["ZENA", "VĚROSLAVA", "České jméno znamenající 'slavící víru'."],
  ["ZENA", "VIKTORIE", "Latinské jméno, které v doslovném překladu znamená 'vítězství'."],
  ["ZENA", "VILMA", "Germánské jméno, které znamená 'vůlí chráněná'."],
  ["ZENA", "VINCENCIE", "Latinské jméno, které v překladu znamená 'vítězící'."],
  ["ZENA", "VIOLA", "Latinské jméno, které v doslovném překladu znamená 'fialka'."],
  ["ZENA", "VLASTA", "Slovanské jméno znamenající 'tu, která patří k vlasti'."],
  ["ZENA", "VLASTIMILA", "České jméno znamenající 'milující svou vlast'."],
  ["ZENA", "VRAŤKA", "Staré české jméno odvozené od Vratislavy, znamenající 'navrať slávu'."],
  ["ZENA", "XENIE", "Řecké jméno, které v překladu znamená 'pohostinná'."],
  ["ZENA", "ZDENA", "Zkrácenina jména Zdeňka, znamenající 'zde slavná'."],
  ["ZENA", "ZDEŇKA", "České jméno odvozené od Zdislavy, znamenající 'zde slavná'."],
  ["ZENA", "ZDISLAVA", "Slovanské jméno, které v překladu znamená 'zde slavná'."],
  ["ZENA", "ZITA", "Perské jméno, které v překladu znamená 'dívka' nebo 'šťastná'."],
  ["ZENA", "ZLATA", "Slovanské jméno s jasným významem 'zlatá'."],
  ["ZENA", "ZORA", "Slovanské jméno znamenající 'jitřenka' nebo 'úsvit'."],
  ["ZENA", "ZUZANA", "Hebrejské jméno, které v doslovném překladu znamená 'lilie'."],
  ["ZENA", "ŽANETA", "Hebrejské jméno (francouzská varianta), které znamená 'Bůh je milostivý'."],
  ["ZENA", "ŽOFIE", "Řecké jméno, které v překladu znamená 'moudrost'."],

  // --- NEUTRÁLNÍ JMÉNA ---
  ["NEUTRALNI", "ALEX", "Zkrácenina jména Alexandr, která v řečtině znamená 'obránce'."],
  ["NEUTRALNI", "RENE", "Jméno latinského původu, které v překladu znamená 'znovuzrozený'."],
  ["NEUTRALNI", "SAŠA", "Ruská domácká podoba jména Alexandr či Alexandra, znamenající 'obránce'."],
  ["NEUTRALNI", "NIKOLA", "Řecké jméno, které v překladu znamená 'vítěz/vítězka nad lidem'."],
  ["NEUTRALNI", "MICHEL", "Francouzská varianta jména Michael, znamenající 'kdo je jako Bůh?'."]
];

export const NAMES_DATASET: BabyName[] = rawDataset.map(([gender, name, fact]) => ({
  gender: gender as Gender,
  name: name.trim(),
  fact: fact
}));